services:
  postgres:
    image: postgres:17
    container_name: gudar-phonebook-postgres
    environment:
      POSTGRES_DB: phonebook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - phonebook_pgdata:/var/lib/postgresql/data

volumes:
  phonebook_pgdata:
